#!/bin/bash
sudo nvim /var/log/distrobox-import/distrobox-path.log &&
sudo sed -i '/#/d' /var/log/distrobox-import/distrobox-path.log &&
while read -r binary ; do
    if [ -x /"$binary" ]  && [ "$binary" != "usr/bin/" ]; then
    distrobox-export --bin /"$binary" --export-path /home/$USER/.local/bin/archpath
    fi
done < /var/log/distrobox-import/distrobox-path.log
